#.travis.yml

language: node_js
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

node_js:
  - "8.4"

branches:
  only:
    - master

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - export KARMA_SINGLE_RUN=true

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng test
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
