#.travis.yml

language: node_js
node_js:
  - "8.4"

branches:
  only:
    - master

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CHROME_BIN=chromium-browser
  - echo "--no-sandbox" > ~/.config/chromium-flags.conf
  - export KARMA_SINGLE_RUN=true
  - sh -e chmod 755 /usr/lib/chromium-browser/chrome-sandbox

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng test
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
